### ISSUE TITLE
Not getting any results using SPM

### ISSUE THREAD

**Issue by AvdLee** [DataDog/dd-sdk-swift-testing#67]
I've integrated the package using SPM. The SDK I'm trying to integrate is tested on Bitrise CI and only uses SPM. Therefore, there's no way to link the package through the Xcode interface.

~The only way I could make it work is by explicitly adding an import to one of my test files:~ turned out that this didn't fix it on CI. I'm investigating further.

```swift
import DatadogSDKTesting
```

Is there another way to force link the library for SPM Package testing?

**Comment by nachoBonafonte** [comment]
Hi @AvdLee,
The simplest way is by simply adding the the dependency to your package and testTarget dependencies:

- Add: `.package(url: "https://github.com/DataDog/dd-sdk-swift-testing.git", from: "2.1.0")` to the package dependencies array
- Add: `.product(name: "DatadogSDKTesting", package: "dd-sdk-swift-testing")` to the desired  testTarget

These two changes make the framework to be linked in the test target.

After linking you must enable and configure it with the environment variables, a simple way to set them could by just but setting them in the same call to `swift test`, e.g.:

`DD_TEST_RUNNER=1 DD_API_KEY=<your API key> DD_SITE=us1 SRCROOT=$PWD swift test`

With this you should be receiving the results of your tests in your Datadog account. 

PS- I will add this information to the documentation so it can be easily found by anyone

PS2 - The framework logs some status information to stdout with the `[DatadogSDKTesting]` prefix, but `swift test` by default filters all the stdout output, so this messages cannot be seen. I am thinking on logging status to stderr to avoid this problem when using SPM

**Comment by AvdLee** [comment]
Ok, I've struggled quite a bit today to get it working. Locally, `xcodebuild` does log the `[DatadogSDKTesting]` messages and I constantly ran into:

> [DatadogSDKTesting] Library loaded but not active, DD_TEST_RUNNER is missing

Turned out, based on [this answer](https://stackoverflow.com/a/69237460) you need to prefix environment variables with `TEST_RUNNER_`:

> xcodebuild now supports passing certain environment variables to test runner processes. In the environment where xcodebuild is invoked, prefix any variable with TEST_RUNNER_ to pass that variable (with the prefix stripped) to XCTest test runner processes. For example, running env TEST_RUNNER_Foo=Bar xcodebuild test ... causes the environment variable Foo=Bar to be set in the test runner’s environment. (74104870)

I'm now running improvements on Bitrise CI to see if I can make this work. T.b.c!

**Comment by nachoBonafonte** [comment]
Oh sorry, I thought that as it was a SPM only project you were using `swift test` command for testing, did not think that you were using `xcodebuild` for running the tests.

**Comment by AvdLee** [comment]
> [DatadogSDKTesting] Library loaded and active. Instrumenting tests.

Yet, no results yet in Datadog. I've used:

```ruby
ENV["TEST_RUNNER_DD_TEST_RUNNER"] = '1' 
ENV["TEST_RUNNER_DD_ENV"] = 'ci' 
ENV["TEST_RUNNER_DD_SITE"] = 'datadoghq.eu'
ENV["TEST_RUNNER_DD_SERVICE"] = scheme
ENV["TEST_RUNNER_DD_API_KEY"] = ENV['DD_API_KEY']
ENV["TEST_RUNNER_SRCROOT"] = ENV['PWD']
```

And I feel like the site is wrong. What do you think @nachoBonafonte?

**Comment by nachoBonafonte** [comment]
Those values for the environment variables look correct:

- ✅  for the endpoint it supports a wide variety of values and your is included:  [related code](https://github.com/DataDog/dd-sdk-swift-testing/blob/698853f77786bc424158f3ae011bfa4fbd1348ba/Sources/DatadogSDKTesting/DDTracer.swift#L74)

- ✅  The values are properly being injected because it says library loaded and active
- ⚠️  As you are running with xcodebuild you may use `$(SRCROOT)` as the value for `TEST_RUNNER_SRCROOT`, as xcode sets that value when running the tests. But that should not make your test fail

The only thing that I think would make it fail is that it is not getting the `DD_API_KEY` value correctly:
* Is it stored in Bitrise secrets? 
* does Bitrise allow for it to be accessed that way from your env variables?
* Have you tried setting something like: ENV["TEST_RUNNER_DD_API_KEY"] =  ´$(DD_API_KEY)´ so it says xcodebuild to read the value from the process environment variables? (Bitrise sets your secrets and environment variables before running the command)

Sorry for not having a definite answer here, as I said that is a scenario I had not expected before (running a .package project in xcodebuild inside Bitrise). I will prepare an example like that in our Bitrise instance and will try to have a final answer for you tomorrow.

PS- There is another environment variable that makes the framework to be much more verbose with the information (probably too much verbose, and usually not verbose enough to find the issue you are looking for) but that may be helpful here: `DD_TRACE_DEBUG=1`

**Comment by AvdLee** [comment]
`DD_TRACE_DEBUG` helped quite a bit, this is what I got:

```
[DatadogSDKTesting] could not find git commit information
[17:10:46]: ▸ [DatadogSDKTesting] could not find git repository information
[17:10:46]: ▸ [DatadogSDKTesting] could not find git branch or tag  information
[17:10:46]: ▸ [DatadogSDKTesting] Please check: https://docs.datadoghq.com/continuous_integration/troubleshooting
[17:10:46]: ▸ [DatadogSDKTesting] SRCROOT is not properly set
[17:10:46]: ▸ [DatadogSDKTesting] Library loaded and active. Instrumenting tests.
[17:10:46]: ▸ [Debug][DatadogSDKTesting] DYLD_LIBRARY_PATH: /Users/vagrant/git/build/derived_data/Build/Products/Debug-iphonesimulator:/Applications/Xcode-14.0.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib
[17:10:46]: ▸ [Debug][DatadogSDKTesting] DSYMFILE enumerating: /Users/vagrant/git/build/derived_data/Build/Products/Debug-iphonesimulator
[17:10:46]: ▸ [Debug][DatadogSDKTesting] DSYMFILE enumerating: /Applications/Xcode-14.0.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib
[17:10:46]: ▸ [Debug][DatadogSDKTesting] DSYMFILES found: []
```

I'm also pretty sure the API key is set correctly:

```
[17:06:25]: ▸ TEST_RUNNER_DD_TEST_RUNNER=1
[17:06:25]: ▸ TEST_RUNNER_DD_ENV=ci
[17:06:25]: ▸ TEST_RUNNER_DD_SITE=datadoghq.eu
[17:06:25]: ▸ TEST_RUNNER_DD_SERVICE=Networking
[17:06:25]: ▸ TEST_RUNNER_DD_API_KEY=[REDACTED]
[17:06:25]: ▸ TEST_RUNNER_DD_TRACE_DEBUG=1
```

I'm going to integrate it in an actual Xcode project now first to see if it actually works using these parameters directly.

**Comment by AvdLee** [comment]
![CleanShot 2022-10-19 at 19 44 29@2x](https://user-images.githubusercontent.com/4329185/196766109-b76701a9-468e-447d-bacb-34a9aba8e528.jpg)

Turns out that it's the GIT stuff that's missing, it's not properly passed by Bitrise. Fixing that now!

**Comment by AvdLee** [comment]
![CleanShot 2022-10-19 at 19 53 31@2x](https://user-images.githubusercontent.com/4329185/196767720-65ce9125-8d17-4969-906f-d2055fe41573.jpg)

Voila!

I had to add this for Bitrise specific: 

```
    ENV["TEST_RUNNER_DD_GIT_REPOSITORY_URL"] = ENV['GIT_REPOSITORY_URL']
    ENV["TEST_RUNNER_DD_GIT_BRANCH"] = ENV['BITRISE_GIT_BRANCH']
    ENV["TEST_RUNNER_DD_GIT_COMMIT_SHA"] = ENV['BITRISE_GIT_COMMIT']
    ENV["TEST_RUNNER_DD_GIT_COMMIT_MESSAGE"] = ENV['BITRISE_GIT_MESSAGE']
    ENV["TEST_RUNNER_DD_GIT_COMMIT_AUTHOR_NAME"] = ENV['GIT_CLONE_COMMIT_AUTHOR_NAME']
```

**Comment by nachoBonafonte** [comment]
Glad it finally worked and you got your results into Datadog 🥳 . 

Not having proper git information should not block the tests to appear in Datadog, although they will only appear in `Test Runs` because `Test` view is branch related and branch name is part of the git info, I will investigate why it was happening. As I said yesterday I will prepare this testing scenario on my side to understand exactly what are the issues and how to improve the documentation so this is not an issue anymore for anyone. 

The Bitrise CI environment variables are specified [here](https://docs.datadoghq.com/continuous_integration/tests/swift/?tab=bitrise), with them it will also report the Bitrise execution information. Also in the document there are some other configuration to disable some of the automatic instrumentation which is enabled by default, or enable some other optional.

If you have any other or issue or doubt, don't hesitate to contact me here or at my Datadog email.

PS-  I will update this post with my findings in my testing if necessary
PS2- We also announced yesterday a new Datadog solution for test impact analysis (Intelligent Test Runner) which is still in private beta but also supporting Swift, I think it is really cool: [youtube](https://youtu.be/Uv1hkseBrM0?t=2515)

**Comment by AvdLee** [comment]
Thanks a lot for your help and quick replies @nachoBonafonte! For now, we're good, it's all working. Yet, it would be helpful if we don't have to forward those environment variables by using `TEST_RUNNER` prefixes. Not sure if that's fixible from your package, though. I guess it at least helps to update the documentation for future implementors with Bitirse 👌 

Oh, and I'm going to check out that video!
